# Generated by Django 2.2 on 2020-07-08 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barks', '0003_bark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bark',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BarkLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barks.Bark')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bark',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='bark_user', through='barks.BarkLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
