# Generated by Django 2.2 on 2020-07-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barks', '0004_auto_20200708_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='bark',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barks.Bark'),
        ),
    ]
