# Generated by Django 2.2 on 2020-07-28 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barks', '0005_bark_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barks', to=settings.AUTH_USER_MODEL),
        ),
    ]
